# Starting from base image
FROM gcr.io/datamechanics/spark:platform-3.1-latest

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

#Install Python & pip
RUN pip3 install pytest 
# Install dependencies via pip
# WORKDIR /usr/src/app