name: make_changelog
outputs:
  version:
    description: 'The version released'
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install npm package
      run: npm install
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Run the package
      run: npm start
      working-directory: ${{ github.action_path }}
      shell: bash

    - id: get_version
      run: "echo \"::set-output name=version::$(cat VERSION.md)\""
      shell: bash
