name: main
on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

jobs:
  set_release_tag:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting git config
        run: |
          git config --global user.email "services@dutchchannels.com"
          git config --global user.name "DutchChannels"

      - id: get_version
        run: 'echo "::set-output name=version::$(cat VERSION.md)"'

      - name: Setting git tag and push
        run: |
          git tag @jesseschouten/playground@${{ steps.get_version.outputs.version }}
          git push origin @jesseschouten/playground@${{ steps.get_version.outputs.version }}
