name: release
on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  set_release_tag:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting git config
        run: |
          git config --global user.email "services@dutchchannels.com"
          git config --global user.name "DutchChannels"

      - id: get_version
        run: echo "{version_file_content}=version::$(cat VERSION.md)"" >> $GITHUB_ENV 

      - name: Setting git tag and push
        run: |
          git tag @dutchchannels/peitho@${{ env.version_file_content }}
          git push origin @dutchchannels/peitho@${{ env.version_file_content }}